(ns effective.source.source
  (:require [no.disassemble :as disassemble]
            [aprint.core :as aprint]))

;;
;; 1) create some code
;; 2) peek the generated code
;; 3) peek the generated bytecode
;;

(defn plus1 [x]
  (inc x))

(plus1 1)

(disassemble/disassemble
  disassemble/disassemble)
