(ns effective.source
  (:require [no.disassemble :as disassemble]
            [aprint.core :as aprint]))

;;
;; 1) create some code
;; 2) peek the generated code
;; 3) peek the generated bytecode
;;

